package com.amin.e_commerce.core.logging.definition;

public enum BusinessEvent {

    // Bootstrap events
    SYSTEM_ADMIN_INITIALIZED,



    // Auth events
    ACCOUNT_REGISTERED,
    PASSWORD_RESET_REQUESTED,


    // Account events
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_VIEWED,
    ACCOUNTS_LISTED,
    ACCOUNT_ROLE_ASSIGNED,
    ACCOUNT_ROLE_REMOVED,
    ACCOUNT_ROLES_ASSIGNED,
    ACCOUNT_ROLES_REPLACED,
    ACCOUNT_PASSWORD_RESET,

    // Role events
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    ROLE_VIEWED,
    ROLES_LISTED,
    ROLE_CAPABILITY_ASSIGNED,
    ROLE_CAPABILITY_REMOVED,


    // Capability events
    CAPABILITY_CREATED,
    CAPABILITY_UPDATED,
    CAPABILITY_DELETED,
    CAPABILITY_VIEWED,
    CAPABILITIES_LISTED,


    // Verification events
    VERIFICATION_TOKEN_GENERATED,
    VERIFICATION_TOKEN_SUCCEEDED,
    VERIFICATION_TOKEN_FAILED,

    // Email events
    EMAIL_QUEUED,
    EMAIL_SENT,
    EMAIL_SEND_FAILED,
    EMAIL_RETRY_STARTED,
    EMAIL_RETRY_SUCCEEDED,
    EMAIL_RETRY_FAILED,


    // Customer events
    CUSTOMER_CREATED,

    // Category events
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    CATEGORY_VIEWED,
    CATEGORIES_LISTED,

    // Product events
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_VIEWED,
    PRODUCTS_LISTED,

}